import { getPeriodicElement, type PeriodicCategory } from '@/src/data/elementsFull'
import type { Element, ElementCategory } from './types'

// CPK colors from the standard Corey-Pauling-Koltun palette.
// Electronegativities are Pauling scale.
// bondingCapacity = number of covalent bonds typically formed (8 - valence for nonmetals;
// equals valence for groups 1–3; 0 for nobles; typical complex-formation counts for d-block).
export const ELEMENTS: readonly Element[] = [
  {
    Z: 1,
    symbol: 'H',
    name: 'Hydrogen',
    mass: 1.008,
    category: 'nonmetal',
    cpkColor: '#FFFFFF',
    shells: [1],
    valence: 1,
    bondingCapacity: 1,
    oxidationStates: [1, -1],
    electronegativity: 2.2,
    vdwRadius: 1.2,
  },
  {
    Z: 2,
    symbol: 'He',
    name: 'Helium',
    mass: 4.003,
    category: 'noble',
    cpkColor: '#D9FFFF',
    shells: [2],
    valence: 2,
    bondingCapacity: 0,
    oxidationStates: [0],
    electronegativity: 0,
    vdwRadius: 1.4,
  },
  {
    Z: 3,
    symbol: 'Li',
    name: 'Lithium',
    mass: 6.94,
    category: 'alkali',
    cpkColor: '#CC80FF',
    shells: [2, 1],
    valence: 1,
    bondingCapacity: 1,
    oxidationStates: [1],
    electronegativity: 0.98,
    vdwRadius: 1.82,
  },
  {
    Z: 4,
    symbol: 'Be',
    name: 'Beryllium',
    mass: 9.012,
    category: 'alkaline',
    cpkColor: '#C2FF00',
    shells: [2, 2],
    valence: 2,
    bondingCapacity: 2,
    oxidationStates: [2],
    electronegativity: 1.57,
    vdwRadius: 1.53,
  },
  {
    Z: 5,
    symbol: 'B',
    name: 'Boron',
    mass: 10.81,
    category: 'metalloid',
    cpkColor: '#FFB5B5',
    shells: [2, 3],
    valence: 3,
    bondingCapacity: 3,
    oxidationStates: [3],
    electronegativity: 2.04,
    vdwRadius: 1.92,
  },
  {
    Z: 6,
    symbol: 'C',
    name: 'Carbon',
    mass: 12.01,
    category: 'nonmetal',
    cpkColor: '#909090',
    shells: [2, 4],
    valence: 4,
    bondingCapacity: 4,
    oxidationStates: [4, -4, 2],
    electronegativity: 2.55,
    vdwRadius: 1.7,
  },
  {
    Z: 7,
    symbol: 'N',
    name: 'Nitrogen',
    mass: 14.01,
    category: 'nonmetal',
    cpkColor: '#3050F8',
    shells: [2, 5],
    valence: 5,
    bondingCapacity: 3,
    oxidationStates: [-3, 3, 5],
    electronegativity: 3.04,
    vdwRadius: 1.55,
  },
  {
    Z: 8,
    symbol: 'O',
    name: 'Oxygen',
    mass: 16.0,
    category: 'nonmetal',
    cpkColor: '#FF0D0D',
    shells: [2, 6],
    valence: 6,
    bondingCapacity: 2,
    oxidationStates: [-2],
    electronegativity: 3.44,
    vdwRadius: 1.52,
  },
  {
    Z: 9,
    symbol: 'F',
    name: 'Fluorine',
    mass: 19.0,
    category: 'halogen',
    cpkColor: '#90E050',
    shells: [2, 7],
    valence: 7,
    bondingCapacity: 1,
    oxidationStates: [-1],
    electronegativity: 3.98,
    vdwRadius: 1.47,
  },
  {
    Z: 10,
    symbol: 'Ne',
    name: 'Neon',
    mass: 20.18,
    category: 'noble',
    cpkColor: '#B3E3F5',
    shells: [2, 8],
    valence: 8,
    bondingCapacity: 0,
    oxidationStates: [0],
    electronegativity: 0,
    vdwRadius: 1.54,
  },
  {
    Z: 11,
    symbol: 'Na',
    name: 'Sodium',
    mass: 22.99,
    category: 'alkali',
    cpkColor: '#AB5CF2',
    shells: [2, 8, 1],
    valence: 1,
    bondingCapacity: 1,
    oxidationStates: [1],
    electronegativity: 0.93,
    vdwRadius: 2.27,
  },
  {
    Z: 12,
    symbol: 'Mg',
    name: 'Magnesium',
    mass: 24.31,
    category: 'alkaline',
    cpkColor: '#8AFF00',
    shells: [2, 8, 2],
    valence: 2,
    bondingCapacity: 2,
    oxidationStates: [2],
    electronegativity: 1.31,
    vdwRadius: 1.73,
  },
  {
    Z: 13,
    symbol: 'Al',
    name: 'Aluminum',
    mass: 26.98,
    category: 'other-metal',
    cpkColor: '#BFA6A6',
    shells: [2, 8, 3],
    valence: 3,
    bondingCapacity: 3,
    oxidationStates: [3],
    electronegativity: 1.61,
    vdwRadius: 1.84,
  },
  {
    Z: 14,
    symbol: 'Si',
    name: 'Silicon',
    mass: 28.09,
    category: 'metalloid',
    cpkColor: '#F0C8A0',
    shells: [2, 8, 4],
    valence: 4,
    bondingCapacity: 4,
    oxidationStates: [4, -4],
    electronegativity: 1.9,
    vdwRadius: 2.1,
  },
  {
    Z: 15,
    symbol: 'P',
    name: 'Phosphorus',
    mass: 30.97,
    category: 'nonmetal',
    cpkColor: '#FF8000',
    shells: [2, 8, 5],
    valence: 5,
    bondingCapacity: 3,
    oxidationStates: [5, 3, -3],
    electronegativity: 2.19,
    vdwRadius: 1.8,
  },
  {
    Z: 16,
    symbol: 'S',
    name: 'Sulfur',
    mass: 32.07,
    category: 'nonmetal',
    cpkColor: '#FFFF30',
    shells: [2, 8, 6],
    valence: 6,
    bondingCapacity: 2,
    oxidationStates: [-2, 4, 6],
    electronegativity: 2.58,
    vdwRadius: 1.8,
  },
  {
    Z: 17,
    symbol: 'Cl',
    name: 'Chlorine',
    mass: 35.45,
    category: 'halogen',
    cpkColor: '#1FF01F',
    shells: [2, 8, 7],
    valence: 7,
    bondingCapacity: 1,
    oxidationStates: [-1, 1, 3, 5, 7],
    electronegativity: 3.16,
    vdwRadius: 1.75,
  },
  {
    Z: 18,
    symbol: 'Ar',
    name: 'Argon',
    mass: 39.95,
    category: 'noble',
    cpkColor: '#80D1E3',
    shells: [2, 8, 8],
    valence: 8,
    bondingCapacity: 0,
    oxidationStates: [0],
    electronegativity: 0,
    vdwRadius: 1.88,
  },
  {
    Z: 19,
    symbol: 'K',
    name: 'Potassium',
    mass: 39.1,
    category: 'alkali',
    cpkColor: '#8F40D4',
    shells: [2, 8, 8, 1],
    valence: 1,
    bondingCapacity: 1,
    oxidationStates: [1],
    electronegativity: 0.82,
    vdwRadius: 2.75,
  },
  {
    Z: 20,
    symbol: 'Ca',
    name: 'Calcium',
    mass: 40.08,
    category: 'alkaline',
    cpkColor: '#3DFF00',
    shells: [2, 8, 8, 2],
    valence: 2,
    bondingCapacity: 2,
    oxidationStates: [2],
    electronegativity: 1.0,
    vdwRadius: 2.31,
  },
  {
    Z: 21,
    symbol: 'Sc',
    name: 'Scandium',
    mass: 44.96,
    category: 'transition',
    cpkColor: '#E6E6E6',
    shells: [2, 8, 9, 2],
    valence: 3,
    bondingCapacity: 3,
    oxidationStates: [3],
    electronegativity: 1.36,
    vdwRadius: 2.11,
  },
  {
    Z: 22,
    symbol: 'Ti',
    name: 'Titanium',
    mass: 47.87,
    category: 'transition',
    cpkColor: '#BFC2C7',
    shells: [2, 8, 10, 2],
    valence: 4,
    bondingCapacity: 4,
    oxidationStates: [2, 3, 4],
    electronegativity: 1.54,
    vdwRadius: 1.87,
  },
  {
    Z: 23,
    symbol: 'V',
    name: 'Vanadium',
    mass: 50.94,
    category: 'transition',
    cpkColor: '#A6A6AB',
    shells: [2, 8, 11, 2],
    valence: 5,
    bondingCapacity: 3,
    oxidationStates: [2, 3, 4, 5],
    electronegativity: 1.63,
    vdwRadius: 1.79,
  },
  {
    Z: 24,
    symbol: 'Cr',
    name: 'Chromium',
    mass: 52.0,
    category: 'transition',
    cpkColor: '#8A99C7',
    shells: [2, 8, 13, 1],
    valence: 6,
    bondingCapacity: 3,
    oxidationStates: [2, 3, 6],
    electronegativity: 1.66,
    vdwRadius: 1.89,
  },
  {
    Z: 25,
    symbol: 'Mn',
    name: 'Manganese',
    mass: 54.94,
    category: 'transition',
    cpkColor: '#9C7AC7',
    shells: [2, 8, 13, 2],
    valence: 7,
    bondingCapacity: 4,
    oxidationStates: [2, 4, 7],
    electronegativity: 1.55,
    vdwRadius: 1.97,
  },
  {
    Z: 26,
    symbol: 'Fe',
    name: 'Iron',
    mass: 55.85,
    category: 'transition',
    cpkColor: '#E06633',
    shells: [2, 8, 14, 2],
    valence: 8,
    bondingCapacity: 3,
    oxidationStates: [2, 3],
    electronegativity: 1.83,
    vdwRadius: 1.94,
  },
  {
    Z: 27,
    symbol: 'Co',
    name: 'Cobalt',
    mass: 58.93,
    category: 'transition',
    cpkColor: '#F090A0',
    shells: [2, 8, 15, 2],
    valence: 9,
    bondingCapacity: 3,
    oxidationStates: [2, 3],
    electronegativity: 1.88,
    vdwRadius: 1.92,
  },
  {
    Z: 28,
    symbol: 'Ni',
    name: 'Nickel',
    mass: 58.69,
    category: 'transition',
    cpkColor: '#50D050',
    shells: [2, 8, 16, 2],
    valence: 10,
    bondingCapacity: 2,
    oxidationStates: [2, 3],
    electronegativity: 1.91,
    vdwRadius: 1.63,
  },
  {
    Z: 29,
    symbol: 'Cu',
    name: 'Copper',
    mass: 63.55,
    category: 'transition',
    cpkColor: '#C88033',
    shells: [2, 8, 18, 1],
    valence: 11,
    bondingCapacity: 2,
    oxidationStates: [1, 2],
    electronegativity: 1.9,
    vdwRadius: 1.4,
  },
  {
    Z: 30,
    symbol: 'Zn',
    name: 'Zinc',
    mass: 65.38,
    category: 'transition',
    cpkColor: '#7D80B0',
    shells: [2, 8, 18, 2],
    valence: 12,
    bondingCapacity: 2,
    oxidationStates: [2],
    electronegativity: 1.65,
    vdwRadius: 1.39,
  },
  {
    Z: 31,
    symbol: 'Ga',
    name: 'Gallium',
    mass: 69.72,
    category: 'other-metal',
    cpkColor: '#C28F8F',
    shells: [2, 8, 18, 3],
    valence: 3,
    bondingCapacity: 3,
    oxidationStates: [3],
    electronegativity: 1.81,
    vdwRadius: 1.87,
  },
  {
    Z: 32,
    symbol: 'Ge',
    name: 'Germanium',
    mass: 72.63,
    category: 'metalloid',
    cpkColor: '#668F8F',
    shells: [2, 8, 18, 4],
    valence: 4,
    bondingCapacity: 4,
    oxidationStates: [4, -4],
    electronegativity: 2.01,
    vdwRadius: 2.11,
  },
  {
    Z: 33,
    symbol: 'As',
    name: 'Arsenic',
    mass: 74.92,
    category: 'metalloid',
    cpkColor: '#BD80E3',
    shells: [2, 8, 18, 5],
    valence: 5,
    bondingCapacity: 3,
    oxidationStates: [-3, 3, 5],
    electronegativity: 2.18,
    vdwRadius: 1.85,
  },
  {
    Z: 34,
    symbol: 'Se',
    name: 'Selenium',
    mass: 78.97,
    category: 'nonmetal',
    cpkColor: '#FFA100',
    shells: [2, 8, 18, 6],
    valence: 6,
    bondingCapacity: 2,
    oxidationStates: [-2, 4, 6],
    electronegativity: 2.55,
    vdwRadius: 1.9,
  },
  {
    Z: 35,
    symbol: 'Br',
    name: 'Bromine',
    mass: 79.9,
    category: 'halogen',
    cpkColor: '#A62929',
    shells: [2, 8, 18, 7],
    valence: 7,
    bondingCapacity: 1,
    oxidationStates: [-1, 1, 5],
    electronegativity: 2.96,
    vdwRadius: 1.85,
  },
  {
    Z: 36,
    symbol: 'Kr',
    name: 'Krypton',
    mass: 83.8,
    category: 'noble',
    cpkColor: '#5CB8D1',
    shells: [2, 8, 18, 8],
    valence: 8,
    bondingCapacity: 0,
    oxidationStates: [0],
    electronegativity: 3.0,
    vdwRadius: 2.02,
  },
] as const

const BY_Z = new Map<number, Element>(ELEMENTS.map((e) => [e.Z, e]))
const BY_SYMBOL = new Map<string, Element>(ELEMENTS.map((e) => [e.symbol, e]))

// Fallback CPK-ish colors by category, used when an element isn't in
// the curated chemistry-engine list above (Z > 36) but still needs to
// render in scenes — e.g. uranium / barium / krypton in the nuclear
// demos. Real CPK has element-specific colors; carrying that data for
// all 118 elements would bloat the bundle, so we approximate with the
// same family-coded palette the periodic-table grid uses.
const FALLBACK_CPK_BY_CATEGORY: Record<PeriodicCategory, string> = {
  alkali: '#AB5CF2',
  alkaline: '#8AFF00',
  transition: '#FFC0CB',
  'post-transition': '#B0B5CC',
  'other-metal': '#B0B5CC',
  metalloid: '#7AD9AA',
  nonmetal: '#5CC6FF',
  halogen: '#C8FF7A',
  noble: '#C89EFF',
  lanthanide: '#FFC8C8',
  actinide: '#FF8888',
}

// Map the wider periodic-table category enum back to the chemistry
// engine's narrower one. Lanthanides + actinides collapse to
// 'transition' (their d-/f-block character is closest to that bucket);
// 'post-transition' collapses to 'other-metal'.
function narrowCategory(p: PeriodicCategory): ElementCategory {
  switch (p) {
    case 'lanthanide':
    case 'actinide':
      return 'transition'
    case 'post-transition':
      return 'other-metal'
    default:
      return p
  }
}

export function getElement(Z: number): Element {
  const el = BY_Z.get(Z)
  if (el) return el
  // Fall back to the full periodic-table dataset for elements outside
  // the chemistry-engine's modelled range. The fallback Element is for
  // RENDERING only — its valence / bondingCapacity / oxidation states
  // are zeroed because the reaction engine doesn't simulate Z > 36.
  // Scenes that just need an atom (demo player, sandbox spawns) still
  // get a correctly-shaped atom with shells + a sensible color.
  const periodic = getPeriodicElement(Z)
  if (periodic) {
    return {
      Z: periodic.Z,
      symbol: periodic.symbol,
      name: periodic.name,
      mass: periodic.mass,
      category: narrowCategory(periodic.category),
      cpkColor: FALLBACK_CPK_BY_CATEGORY[periodic.category] ?? '#9aa0c8',
      shells: [...periodic.shells],
      valence: 0,
      bondingCapacity: 0,
      oxidationStates: [0],
      electronegativity: 0,
      vdwRadius: 1.5,
    }
  }
  throw new Error(`No element with Z=${Z}`)
}

export function getElementBySymbol(symbol: string): Element {
  const el = BY_SYMBOL.get(symbol)
  if (!el) throw new Error(`No element with symbol=${symbol}`)
  return el
}
